# Generated by Django 5.0 on 2024-03-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='User_name',
            new_name='name',
        ),
    ]
