# Generated by Django 5.0 on 2024-03-12 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='userinfo.category'),
        ),
    ]
